/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

/* oxlint-disable react/only-export-components -- The factory exports SVG icon components with forwarded refs. */
import type { LucideProps } from 'lucide-react'
import { forwardRef } from 'react'

import { GameIcon } from './game-icon'

export type { LucideIcon, LucideProps } from 'lucide-react'

/** Keep existing SVG contracts while rendering the original Unity Picto art. */
function createGameIcon(name: string) {
  const Icon = forwardRef<SVGSVGElement, LucideProps>(function UnityPictoIcon(
    { absoluteStrokeWidth: _absoluteStrokeWidth, ...props },
    ref
  ) {
    return <GameIcon {...props} ref={ref} name={name} />
  })
  Icon.displayName = `UnityPicto(${name})`
  return Icon
}

export const Activity = createGameIcon('chart')
export const AlertCircle = createGameIcon('symbol-warning')
export const AlertTriangle = createGameIcon('mark-warning')
export const AreaChart = createGameIcon('chart')
export const ArrowDown = createGameIcon('arrow-bottom')
export const ArrowDownIcon = createGameIcon('arrow-bottom')
export const ArrowDownRight = createGameIcon('arrow-bottom')
export const ArrowLeft = createGameIcon('arrow-left')
export const ArrowLeftIcon = createGameIcon('arrow-left')
export const ArrowRight = createGameIcon('arrow-right')
export const ArrowRightIcon = createGameIcon('arrow-right')
export const ArrowRightLeft = createGameIcon('arrow-change')
export const ArrowUp = createGameIcon('arrow-top')
export const ArrowUpDown = createGameIcon('arrow-change')
export const ArrowUpFromLine = createGameIcon('export')
export const ArrowUpRight = createGameIcon('export')
export const Ban = createGameIcon('block')
export const BarChart3 = createGameIcon('chart')
export const BarChartIcon = createGameIcon('chart')
export const Bell = createGameIcon('bell-1')
export const Blend = createGameIcon('mix')
export const BookIcon = createGameIcon('book-1')
export const BookOpen = createGameIcon('book-1')
export const Box = createGameIcon('category-1')
export const Boxes = createGameIcon('category-2')
export const Braces = createGameIcon('paper-3')
export const BrainIcon = createGameIcon('brain')
export const Building2 = createGameIcon('bank')
export const Calendar = createGameIcon('calendar')
export const CalendarClock = createGameIcon('date')
export const CalendarDays = createGameIcon('calendar')
export const CameraIcon = createGameIcon('camera-1')
export const Check = createGameIcon('mark-check')
export const CheckCircle2 = createGameIcon('symbol-check')
export const CheckCircleIcon = createGameIcon('symbol-check')
export const CheckIcon = createGameIcon('mark-check')
export const CheckSquare = createGameIcon('certify')
export const ChevronDown = createGameIcon('arrow-bottom')
export const ChevronDownIcon = createGameIcon('arrow-bottom')
export const ChevronLeft = createGameIcon('arrow-prev')
export const ChevronLeftIcon = createGameIcon('arrow-prev')
export const ChevronRight = createGameIcon('arrow-next')
export const ChevronRightIcon = createGameIcon('arrow-next')
export const ChevronUp = createGameIcon('arrow-top')
export const ChevronsLeft = createGameIcon('player-skip-rw')
export const ChevronsRight = createGameIcon('player-skip-fw')
export const ChevronsUpDown = createGameIcon('arrow-change')
export const ChevronsUpDownIcon = createGameIcon('arrow-change')
export const Circle = createGameIcon('certify-line')
export const CircleAlert = createGameIcon('symbol-warning')
export const CircleCheck = createGameIcon('symbol-check')
export const CircleIcon = createGameIcon('hourglass')
export const CircleQuestionMark = createGameIcon('symbol-question')
export const ClockIcon = createGameIcon('time-1')
export const Cloud = createGameIcon('cloud')
export const Code = createGameIcon('paper-3')
export const Code2 = createGameIcon('paper-3')
export const CodeSquareIcon = createGameIcon('paper-3')
export const Coins = createGameIcon('coin-2')
export const Construction = createGameIcon('tool-1')
export const Copy = createGameIcon('layer-1')
export const CopyIcon = createGameIcon('layer-1')
export const CpuIcon = createGameIcon('brain')
export const CreditCard = createGameIcon('cards')
export const Crown = createGameIcon('crown-1')
export const Database = createGameIcon('layer-2')
export const DollarSign = createGameIcon('money')
export const DotIcon = createGameIcon('bullet-1')
export const Download = createGameIcon('download')
export const DownloadIcon = createGameIcon('download')
export const Edit = createGameIcon('write')
export const Ellipsis = createGameIcon('menu-2')
export const Eraser = createGameIcon('brush')
export const ExternalLink = createGameIcon('export')
export const ExternalLinkIcon = createGameIcon('export')
export const Eye = createGameIcon('eye-show')
export const EyeOff = createGameIcon('eye-hide')
export const FileCode2 = createGameIcon('paper-3')
export const FileIcon = createGameIcon('paper-1')
export const FileText = createGameIcon('paper-2')
export const FileWarning = createGameIcon('notice')
export const Filter = createGameIcon('filter')
export const Flame = createGameIcon('fire')
export const Gauge = createGameIcon('speed')
export const Gift = createGameIcon('gift-1')
export const GitBranch = createGameIcon('road-sign')
export const Globe = createGameIcon('globe')
export const GlobeIcon = createGameIcon('globe')
export const GraduationCapIcon = createGameIcon('learn')
export const Grid2X2 = createGameIcon('category-1')
export const GripVertical = createGameIcon('move')
export const HardDrive = createGameIcon('save')
export const Hash = createGameIcon('category-2')
export const Headphones = createGameIcon('audio')
export const HeartHandshake = createGameIcon('hand-like')
export const HeartPulse = createGameIcon('hp')
export const HelpCircle = createGameIcon('symbol-question')
export const Home = createGameIcon('home-1')
export const House = createGameIcon('home-1')
export const ImageIcon = createGameIcon('photo')
export const Info = createGameIcon('symbol-info')
export const Key = createGameIcon('key-1')
export const KeyRound = createGameIcon('key-1')
export const Landmark = createGameIcon('bank')
export const Languages = createGameIcon('earth')
export const Laptop = createGameIcon('monitor')
export const Layers = createGameIcon('layer-2')
export const Layers3 = createGameIcon('layer-2')
export const LayersIcon = createGameIcon('layer-2')
export const Layout = createGameIcon('dashboard')
export const LayoutDashboard = createGameIcon('dashboard')
export const Lightbulb = createGameIcon('bulb')
export const Link = createGameIcon('link-1')
export const Link2 = createGameIcon('link-2')
export const List = createGameIcon('menu-1')
export const ListChecks = createGameIcon('quest')
export const ListOrdered = createGameIcon('ranking-1')
export const ListTodo = createGameIcon('quest')
export const Loader2 = createGameIcon('refresh')
export const Loader2Icon = createGameIcon('refresh')
export const LogIn = createGameIcon('entrance')
export const LogOut = createGameIcon('exit')
export const Mail = createGameIcon('mail')
export const Maximize2 = createGameIcon('window-max')
export const Megaphone = createGameIcon('megaphone')
export const Menu = createGameIcon('menu-2')
export const MessageCircle = createGameIcon('message-1')
export const MessageCircleIcon = createGameIcon('message-1')
export const MessageCircleWarning = createGameIcon('notice')
export const MessageSquare = createGameIcon('message-2')
export const MessageSquarePlusIcon = createGameIcon('bubble-typing')
export const MicIcon = createGameIcon('mic')
export const Minus = createGameIcon('mark-minus')
export const Monitor = createGameIcon('monitor')
export const Moon = createGameIcon('moon')
export const MoonStar = createGameIcon('moon')
export const MoreHorizontal = createGameIcon('menu-2')
export const MousePointerClick = createGameIcon('hand')
export const Move = createGameIcon('move')
export const Music = createGameIcon('music-on')
export const NotepadTextIcon = createGameIcon('news-1')
export const Package = createGameIcon('category-2')
export const Paintbrush = createGameIcon('brush')
export const Palette = createGameIcon('color')
export const PaperclipIcon = createGameIcon('clip')
export const Pencil = createGameIcon('pencil')
export const PieChart = createGameIcon('chart')
export const PlayIcon = createGameIcon('player-play')
export const PlugZap = createGameIcon('energy')
export const Plus = createGameIcon('mark-plus')
export const PlusCircle = createGameIcon('symbol-plus')
export const PlusIcon = createGameIcon('mark-plus')
export const Power = createGameIcon('switch')
export const PowerOff = createGameIcon('quit')
export const Presentation = createGameIcon('monitor')
export const QrCode = createGameIcon('scan')
export const Radio = createGameIcon('wifi')
export const RadioTower = createGameIcon('wifi')
export const Receipt = createGameIcon('paper-2')
export const RefreshCcw = createGameIcon('refresh')
export const RefreshCcwIcon = createGameIcon('refresh')
export const RefreshCw = createGameIcon('refresh')
export const RotateCcw = createGameIcon('rotate')
export const RotateCw = createGameIcon('rotate')
export const Route = createGameIcon('road-sign')
export const Save = createGameIcon('save')
export const Scissors = createGameIcon('pick')
export const ScreenShareIcon = createGameIcon('export')
export const ScrollText = createGameIcon('scroll')
export const Search = createGameIcon('search')
export const SearchIcon = createGameIcon('search')
export const Send = createGameIcon('send')
export const SendIcon = createGameIcon('send')
export const Server = createGameIcon('layer-2')
export const ServerCog = createGameIcon('setting-3')
export const Settings = createGameIcon('setting-1')
export const Settings2 = createGameIcon('setting-2')
export const Share2 = createGameIcon('share')
export const Shield = createGameIcon('shield')
export const ShieldAlert = createGameIcon('shield')
export const ShieldCheck = createGameIcon('shield')
export const Shuffle = createGameIcon('mix')
export const Sigma = createGameIcon('category-2')
export const SlidersHorizontal = createGameIcon('control-1')
export const SortAsc = createGameIcon('ranking-1')
export const Sparkles = createGameIcon('wand-star')
export const SquareIcon = createGameIcon('mark-x')
export const Sun = createGameIcon('sun')
export const Table = createGameIcon('dashboard')
export const Table2 = createGameIcon('dashboard')
export const Tag = createGameIcon('tag')
export const Tags = createGameIcon('tag')
export const Telescope = createGameIcon('binoculars')
export const Terminal = createGameIcon('monitor')
export const TerminalSquare = createGameIcon('monitor')
export const TestTube = createGameIcon('flask-1')
export const Ticket = createGameIcon('coupon-1')
export const Timer = createGameIcon('timer')
export const Trash2 = createGameIcon('delete-1')
export const Trash2Icon = createGameIcon('delete-1')
export const TrendingDown = createGameIcon('grade-down')
export const TrendingUp = createGameIcon('grade-up')
export const Trophy = createGameIcon('trophy-1')
export const Unlink = createGameIcon('link-2')
export const Upload = createGameIcon('export')
export const User = createGameIcon('user-1')
export const UserCog = createGameIcon('setting-3')
export const UserRound = createGameIcon('user-1')
export const Users = createGameIcon('friend')
export const Video = createGameIcon('video')
export const Wallet = createGameIcon('money-bag')
export const WalletCards = createGameIcon('money')
export const Wand2 = createGameIcon('wand-magic')
export const WandSparkles = createGameIcon('wand-star')
export const Webhook = createGameIcon('link-1')
export const WifiOff = createGameIcon('wifi-off')
export const Wrench = createGameIcon('tool-1')
export const WrenchIcon = createGameIcon('tool-1')
export const X = createGameIcon('mark-x')
export const XCircle = createGameIcon('symbol-x')
export const XCircleIcon = createGameIcon('symbol-x')
export const XIcon = createGameIcon('mark-x')
export const Zap = createGameIcon('energy')
export const ZoomIn = createGameIcon('zoomin')
